"""
production_helpers.py

GENERATED by tools/vendor_md_openmm.py from MD_openmm/openmm_production.py.
Do not edit by hand: change MD_openmm and re-run the tool.

Contains the imports and function definitions of that script, verbatim
(bare omm_* imports made package-relative). Its top-level run code is
omitted; sumd_openmm.omm_setup.build_simulation mirrors it.

Functions: strip_comment, read_key_value_file, normalize_none, get_str, get_int, get_float, get_bool, get_genvel, get_nonbonded_method, get_constraints, get_membrane_xy_mode, get_membrane_z_mode, build_inputs, read_file_head_bytes, head_as_text, file_text_contains, looks_like_openmm_xml_state, openmm_xml_state_has_velocities, detect_coordinate_file_type, extract_openmm_xml_step_and_time, load_amber_coordinates, coordinate_has_velocities, set_box_vectors_from_coordinate_object, use_velocities_from_coordinate_object, load_openmm_xml_state_as_coordinate_file, load_openmm_checkpoint_as_coordinate_file, load_amber_restart_as_coordinate_file, load_gromacs_gro_as_coordinate_file, load_charmm_coordinate_as_coordinate_file, load_coordinate_file_auto, write_amber_restart
"""

from __future__ import print_function
import argparse
import datetime
import os
import sys
import time
import xml.etree.ElementTree as ET
from types import SimpleNamespace
from openmm import *
from openmm.app import *
from openmm.unit import *
from .omm_vfswitch import *
from .omm_barostat import *
from .omm_restraints import *
from .omm_rewrap import *
def strip_comment(line):
    return line.split("#", 1)[0].strip()

def read_key_value_file(filename):
    data = {}

    with open(filename, "r") as f:
        for raw in f:
            line = strip_comment(raw)

            if not line:
                continue

            if "=" not in line:
                continue

            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip()

            data[key] = value

    return data

def normalize_none(value):
    if value is None:
        return None

    v = str(value).strip()

    if v.lower() in ["none", "no", "null", "nil", "-", ""]:
        return None

    return v

def get_str(data, key, default=None, required=False):
    if key in data:
        return data[key]

    if required:
        sys.exit("Missing required key in input file: %s" % key)

    return default

def get_int(data, key, default=None, required=False):
    value = get_str(data, key, default, required)

    if value is None:
        return None

    return int(value)

def get_float(data, key, default=None, required=False):
    value = get_str(data, key, default, required)

    if value is None:
        return None

    return float(value)

def get_bool(data, key, default=False):
    if key not in data:
        return bool(default)

    value = str(data[key]).strip().lower()

    if value in ["yes", "true", "on", "1"]:
        return True

    if value in ["no", "false", "off", "0"]:
        return False

    sys.exit("Invalid yes/no value for %s: %s" % (key, data[key]))

def get_genvel(data):
    """
    Velocity policy.

    Default:
        genvel = yes

    genvel = yes:
        Generate new velocities from temp after coordinate_file is loaded.

    genvel = no:
        Do not generate new velocities.
        Use velocities from coordinate_file.
        Stop if coordinate_file has no velocities.

    Legacy compatibility:
        If old key generate_velocities_if_missing exists, use it as genvel.
    """

    if "genvel" in data:
        return get_bool(data, "genvel", True)

    if "generate_velocities_if_missing" in data:
        return get_bool(data, "generate_velocities_if_missing", True)

    return True

def get_nonbonded_method(name):
    value = str(name).strip()

    mapping = {
        "NoCutoff": NoCutoff,
        "CutoffNonPeriodic": CutoffNonPeriodic,
        "CutoffPeriodic": CutoffPeriodic,
        "PME": PME,
        "Ewald": Ewald,
        "LJPME": LJPME,
    }

    if value not in mapping:
        sys.exit("Unknown coulomb/nonbonded method: %s" % value)

    return mapping[value]

def get_constraints(name):
    value = str(name).strip()

    mapping = {
        "None": None,
        "none": None,
        "HBonds": HBonds,
        "AllBonds": AllBonds,
        "HAngles": HAngles,
    }

    if value not in mapping:
        sys.exit("Unknown constraints option: %s" % value)

    return mapping[value]

def get_membrane_xy_mode(name):
    value = str(name).strip()

    mapping = {
        "XYIsotropic": MonteCarloMembraneBarostat.XYIsotropic,
        "XYAnisotropic": MonteCarloMembraneBarostat.XYAnisotropic,
    }

    if value not in mapping:
        sys.exit(
            "Unknown p_XYMode: %s\n"
            "Allowed values: %s"
            % (value, ", ".join(sorted(mapping.keys())))
        )

    return mapping[value]

def get_membrane_z_mode(name):
    value = str(name).strip()

    mapping = {
        "ZFree": MonteCarloMembraneBarostat.ZFree,
        "ZFixed": MonteCarloMembraneBarostat.ZFixed,
        "ConstantVolume": MonteCarloMembraneBarostat.ConstantVolume,
    }

    if value not in mapping:
        sys.exit(
            "Unknown p_ZMode: %s\n"
            "Allowed values: %s"
            % (value, ", ".join(sorted(mapping.keys())))
        )

    return mapping[value]

def build_inputs(data):
    inputs = SimpleNamespace()

    inputs.nstep = get_int(data, "nstep", required=True)
    inputs.dt = get_float(data, "dt", required=True)

    inputs.nstout = get_int(data, "nstout", 1000)
    inputs.nstdcd = get_int(data, "nstdcd", 1000)

    inputs.coulomb_name = get_str(data, "coulomb", "PME")
    inputs.coulomb = get_nonbonded_method(inputs.coulomb_name)

    inputs.ewald_Tol = get_float(data, "ewald_Tol", 0.0005)

    inputs.vdw = get_str(data, "vdw", "Force-switch")
    inputs.r_on = get_float(data, "r_on", 1.0)
    inputs.r_off = get_float(data, "r_off", 1.2)

    inputs.temp = get_float(data, "temp", 310.0)
    inputs.fric_coeff = get_float(data, "fric_coeff", 1.0)

    inputs.pcouple = get_str(data, "pcouple", "yes")
    inputs.p_ref = get_float(data, "p_ref", 1.0)
    inputs.p_type = get_str(data, "p_type", "membrane")

    inputs.p_XYMode_name = get_str(data, "p_XYMode", "XYIsotropic")
    inputs.p_ZMode_name = get_str(data, "p_ZMode", "ZFree")

    inputs.p_XYMode = get_membrane_xy_mode(inputs.p_XYMode_name)
    inputs.p_ZMode = get_membrane_z_mode(inputs.p_ZMode_name)

    inputs.p_tens = get_float(data, "p_tens", 0.0)
    inputs.p_tens_input = inputs.p_tens

    inputs.p_freq = get_int(data, "p_freq", 100)

    inputs.cons_name = get_str(data, "cons", "HBonds")
    inputs.cons = get_constraints(inputs.cons_name)

    inputs.rest = get_str(data, "rest", "no")
    inputs.lj_lrc = get_str(data, "lj_lrc", "no")
    inputs.e14scale = get_float(data, "e14scale", 1.0)

    return inputs

def read_file_head_bytes(filename, nbytes=8192):
    with open(filename, "rb") as f:
        return f.read(nbytes)

def head_as_text(head_bytes):
    try:
        return head_bytes.decode("utf-8", errors="ignore").lstrip()
    except Exception:
        return ""

def file_text_contains(filename, text):
    try:
        with open(filename, "r") as f:
            content = f.read()
    except Exception:
        return False

    return text in content

def looks_like_openmm_xml_state(filename):
    try:
        head = read_file_head_bytes(filename, 8192)
    except Exception:
        return False

    text = head_as_text(head)

    if text.startswith("<?xml") and "<State" in text[:2000]:
        return True

    if text.startswith("<State"):
        return True

    return False

def openmm_xml_state_has_velocities(filename):
    return file_text_contains(filename, "<Velocities>")

def detect_coordinate_file_type(filename):
    """
    coordinate_file is the only starting file, like Amber -c.

    Returns one of:
        openmm_checkpoint
        openmm_xml_state
        amber_restart
        gromacs_gro
        charmm_coordinate
        unknown
    """

    if not os.path.exists(filename):
        sys.exit("coordinate_file does not exist: %s" % filename)

    lower = filename.lower()

    if lower.endswith(".chk"):
        return "openmm_checkpoint"

    if looks_like_openmm_xml_state(filename):
        return "openmm_xml_state"

    if lower.endswith(".xml"):
        return "openmm_xml_state"

    if lower.endswith(".gro"):
        return "gromacs_gro"

    if lower.endswith((".rst7", ".rst", ".inpcrd", ".crd", ".ncrst", ".restrt")):
        return "amber_restart"

    if lower.endswith((".cor", ".pdb")):
        return "charmm_coordinate"

    return "unknown"

def extract_openmm_xml_step_and_time(filename):
    try:
        root = ET.parse(filename).getroot()
    except Exception:
        return None, None

    step_count = None
    time_ps = None

    if "stepCount" in root.attrib:
        try:
            step_count = int(root.attrib["stepCount"])
        except Exception:
            step_count = None

    if "time" in root.attrib:
        try:
            time_ps = float(root.attrib["time"])
        except Exception:
            time_ps = None

    return step_count, time_ps

def load_amber_coordinates(filename):
    """
    Load AMBER coordinates or restart.

    First tries to load positions, velocities, and box.
    If velocities are absent, falls back to positions and box.
    """

    try:
        crd = AmberInpcrdFile(
            filename,
            loadVelocities=True,
            loadBoxVectors=True,
        )
    except Exception:
        crd = AmberInpcrdFile(
            filename,
            loadBoxVectors=True,
        )

    return crd

def coordinate_has_velocities(crd):
    return hasattr(crd, "velocities") and crd.velocities is not None

def set_box_vectors_from_coordinate_object(simulation, crd):
    if hasattr(crd, "boxVectors") and crd.boxVectors is not None:
        simulation.context.setPeriodicBoxVectors(*crd.boxVectors)
        return True

    if hasattr(crd, "getPeriodicBoxVectors"):
        box_vectors = crd.getPeriodicBoxVectors()

        if box_vectors is not None:
            simulation.context.setPeriodicBoxVectors(*box_vectors)
            return True

    return False

def use_velocities_from_coordinate_object(simulation, crd, source_name, required=True):
    if coordinate_has_velocities(crd):
        simulation.context.setVelocities(crd.velocities)
        print("Using velocities from:", source_name)
        return True

    message = "No velocities found in: %s" % source_name

    if required:
        sys.exit(
            message
            + "\n"
            + "genvel = no was requested, so the run cannot start without velocities."
        )

    print(message)
    return False

def load_openmm_xml_state_as_coordinate_file(simulation, filename, genvel):
    print("\nLoading coordinate_file as OpenMM XML state:", filename)

    has_vel = openmm_xml_state_has_velocities(filename)

    if (not genvel) and (not has_vel):
        sys.exit(
            "coordinate_file is an OpenMM XML state, but it has no <Velocities> block:\n"
            "%s\n"
            "genvel = no was requested, so the run cannot start without velocities."
            % filename
        )

    with open(filename, "r") as f:
        state_xml = f.read()

    state = XmlSerializer.deserialize(state_xml)
    simulation.context.setState(state)

    step_count, time_ps = extract_openmm_xml_step_and_time(filename)

    if step_count is not None:
        simulation.currentStep = step_count
        print("OpenMM XML stepCount:", step_count)

    if time_ps is not None:
        print("OpenMM XML time: %.6f ps" % time_ps)

    return {
        "kind": "openmm_xml_state",
        "coordinate_object": None,
        "velocity_source": filename,
        "has_velocities": has_vel,
        "step_count": step_count,
        "time_ps": time_ps,
    }

def load_openmm_checkpoint_as_coordinate_file(simulation, filename):
    print("\nLoading coordinate_file as OpenMM checkpoint:", filename)

    loaded_with_simulation = False

    try:
        simulation.loadCheckpoint(filename)
        loaded_with_simulation = True
    except Exception as exc:
        print(
            "WARNING: simulation.loadCheckpoint failed: %s" % exc,
            file=sys.stderr,
        )
        print(
            "Trying simulation.context.loadCheckpoint instead.",
            file=sys.stderr,
        )

        with open(filename, "rb") as f:
            simulation.context.loadCheckpoint(f.read())

    if loaded_with_simulation:
        print("Loaded checkpoint with simulation.loadCheckpoint.")
    else:
        print("Loaded checkpoint with context.loadCheckpoint.")

    return {
        "kind": "openmm_checkpoint",
        "coordinate_object": None,
        "velocity_source": filename,
        "has_velocities": True,
        "step_count": int(simulation.currentStep),
        "time_ps": None,
    }

def load_amber_restart_as_coordinate_file(simulation, filename, fftype):
    if fftype != "AMBER":
        sys.exit(
            "coordinate_file looks like an AMBER restart, but force_field is not AMBER:\n"
            "%s" % filename
        )

    print("\nLoading coordinate_file as AMBER restart or coordinate:", filename)

    crd = load_amber_coordinates(filename)

    simulation.context.setPositions(crd.positions)
    set_box_vectors_from_coordinate_object(simulation, crd)

    return {
        "kind": "amber_restart",
        "coordinate_object": crd,
        "velocity_source": filename,
        "has_velocities": coordinate_has_velocities(crd),
        "step_count": None,
        "time_ps": None,
    }

def load_gromacs_gro_as_coordinate_file(simulation, filename, fftype):
    if fftype != "GROMACS":
        sys.exit(
            "coordinate_file looks like a GROMACS .gro file, but force_field is not GROMACS:\n"
            "%s" % filename
        )

    print("\nLoading coordinate_file as GROMACS GRO:", filename)

    gro = GromacsGroFile(filename)

    simulation.context.setPositions(gro.positions)
    simulation.context.setPeriodicBoxVectors(*gro.getPeriodicBoxVectors())

    return {
        "kind": "gromacs_gro",
        "coordinate_object": gro,
        "velocity_source": filename,
        "has_velocities": coordinate_has_velocities(gro),
        "step_count": None,
        "time_ps": None,
    }

def load_charmm_coordinate_as_coordinate_file(simulation, filename, fftype):
    if fftype != "CHARMM":
        sys.exit(
            "coordinate_file looks like a CHARMM or PDB coordinate file, but force_field is not CHARMM:\n"
            "%s" % filename
        )

    print("\nLoading coordinate_file as CHARMM coordinate:", filename)

    from .omm_readparams import read_crd

    crd = read_crd(filename, "CHARMM")

    simulation.context.setPositions(crd.positions)

    return {
        "kind": "charmm_coordinate",
        "coordinate_object": crd,
        "velocity_source": filename,
        "has_velocities": coordinate_has_velocities(crd),
        "step_count": None,
        "time_ps": None,
    }

def load_coordinate_file_auto(simulation, filename, fftype, genvel):
    """
    Load coordinate_file automatically.

    This is the Amber -c equivalent.
    There is no input_restart.
    """

    detected = detect_coordinate_file_type(filename)

    print("\ncoordinate_file auto-detection")
    print("coordinate_file:", filename)
    print("Detected coordinate_file type:", detected)

    if detected == "openmm_checkpoint":
        return load_openmm_checkpoint_as_coordinate_file(simulation, filename)

    if detected == "openmm_xml_state":
        return load_openmm_xml_state_as_coordinate_file(simulation, filename, genvel)

    if detected == "amber_restart":
        return load_amber_restart_as_coordinate_file(simulation, filename, fftype)

    if detected == "gromacs_gro":
        return load_gromacs_gro_as_coordinate_file(simulation, filename, fftype)

    if detected == "charmm_coordinate":
        return load_charmm_coordinate_as_coordinate_file(simulation, filename, fftype)

    print("coordinate_file type was unknown. Trying fallback loading.")

    if looks_like_openmm_xml_state(filename):
        return load_openmm_xml_state_as_coordinate_file(simulation, filename, genvel)

    if fftype == "AMBER":
        try:
            return load_amber_restart_as_coordinate_file(simulation, filename, fftype)
        except Exception as exc:
            sys.exit(
                "Could not load coordinate_file as AMBER restart or coordinate:\n"
                "%s\n"
                "Original error: %s" % (filename, exc)
            )

    sys.exit(
        "Could not auto-detect coordinate_file type:\n"
        "%s\n"
        "Use AMBER rst7/inpcrd/ncrst, OpenMM XML state, OpenMM .chk, GROMACS .gro, or CHARMM coordinate."
        % filename
    )

def write_amber_restart(simulation, filename, netcdf=False, enforce_pbc=True):
    try:
        from parmed.openmm.reporters import RestartReporter
    except ImportError:
        print(
            "WARNING: ParmEd not found. Cannot write AMBER restart: %s" % filename,
            file=sys.stderr,
        )
        return None

    try:
        state = simulation.context.getState(
            getPositions=True,
            getVelocities=True,
            enforcePeriodicBox=enforce_pbc,
        )

        reporter = RestartReporter(
            filename,
            1,
            write_multiple=False,
            netcdf=netcdf,
        )

        reporter.report(simulation, state)

        if hasattr(reporter, "finalize"):
            try:
                reporter.finalize()
            except Exception:
                pass

        return filename

    except Exception as exc:
        print(
            "WARNING: failed to write AMBER restart %s: %s" % (filename, exc),
            file=sys.stderr,
        )
        return None
