#!/usr/bin/env python3
"""
vendor_md_openmm.py

Copy the parts of MD_openmm that sumd_openmm uses into the package, so the
package runs on its own:

    python tools/vendor_md_openmm.py /path/to/MD_openmm

Writes src/sumd_openmm/md_openmm/:

  production_helpers.py   every import and FUNCTION DEFINITION of
                          openmm_production.py, verbatim and in order. The
                          script's top-level run code is left out (it would
                          start a simulation on import).
  omm_barostat.py, omm_rewrap.py, omm_vfswitch.py, omm_restraints.py,
  omm_readparams.py       verbatim copies (CHARMM-GUI headers kept).
  PROVENANCE.txt          source path, git commit, sha256 of every source.

The only edit is mechanical: bare imports between these files
("from omm_vfswitch import *") become package-relative
("from .omm_vfswitch import *"). Re-run this after changing MD_openmm, then
run the tests.
"""

import argparse
import ast
import datetime
import hashlib
import os
import re
import subprocess
import sys

MODULES = ["omm_barostat.py", "omm_rewrap.py", "omm_vfswitch.py", "omm_restraints.py", "omm_readparams.py"]
PRODUCTION = "openmm_production.py"

HERE = os.path.dirname(os.path.abspath(__file__))
DEST = os.path.join(HERE, "..", "src", "sumd_openmm", "md_openmm")

_BARE = re.compile(r"^(\s*)from (omm_\w+) import", re.M)


def relativise(src):
    return _BARE.sub(r"\1from .\2 import", src)


def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def git_commit(path):
    try:
        out = subprocess.run(["git", "-C", path, "log", "-1", "--format=%H %ad %s"],
                             capture_output=True, text=True, check=True)
        dirty = subprocess.run(["git", "-C", path, "status", "--porcelain", "--"] + MODULES + [PRODUCTION],
                               capture_output=True, text=True).stdout.strip()
        return out.stdout.strip() + ("  (UNCOMMITTED CHANGES in vendored files)" if dirty else "")
    except Exception:
        return "not a git checkout"


def production_helpers(src_path):
    with open(src_path) as f:
        src = f.read()

    tree = ast.parse(src, filename=src_path)
    parts = [ast.get_source_segment(src, n) for n in tree.body
             if isinstance(n, (ast.Import, ast.ImportFrom, ast.FunctionDef))]

    funcs = [n.name for n in tree.body if isinstance(n, ast.FunctionDef)]
    header = (
        '"""\n'
        "production_helpers.py\n\n"
        "GENERATED by tools/vendor_md_openmm.py from MD_openmm/openmm_production.py.\n"
        "Do not edit by hand: change MD_openmm and re-run the tool.\n\n"
        "Contains the imports and function definitions of that script, verbatim\n"
        "(bare omm_* imports made package-relative). Its top-level run code is\n"
        "omitted; sumd_openmm.omm_setup.build_simulation mirrors it.\n\n"
        "Functions: %s\n"
        '"""\n\n' % ", ".join(funcs)
    )

    body = []
    for p in parts:
        body.append(p)
        body.append("\n\n" if p.startswith(("def ", "@")) else "\n")

    # a __future__ import must stay the first statement after the docstring
    return header + relativise("".join(body)).rstrip() + "\n", funcs


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("md_openmm_dir")
    ap.add_argument("--dest", default=DEST)
    args = ap.parse_args()

    src_dir = os.path.abspath(args.md_openmm_dir)
    dest = os.path.abspath(args.dest)

    missing = [m for m in MODULES + [PRODUCTION] if not os.path.isfile(os.path.join(src_dir, m))]
    if missing:
        sys.exit("not an MD_openmm checkout (missing %s): %s" % (", ".join(missing), src_dir))

    os.makedirs(dest, exist_ok=True)

    text, funcs = production_helpers(os.path.join(src_dir, PRODUCTION))
    with open(os.path.join(dest, "production_helpers.py"), "w") as f:
        f.write(text)

    for m in MODULES:
        with open(os.path.join(src_dir, m)) as f:
            src = f.read()
        with open(os.path.join(dest, m), "w") as f:
            f.write(relativise(src))

    init = os.path.join(dest, "__init__.py")
    with open(init, "w") as f:
        f.write('"""\nBundled helpers from MD_openmm (see PROVENANCE.txt).\n\n'
                "Regenerate with: python tools/vendor_md_openmm.py /path/to/MD_openmm\n"
                'Importing these modules requires OpenMM.\n"""\n')

    with open(os.path.join(dest, "PROVENANCE.txt"), "w") as f:
        f.write("Vendored from MD_openmm\n")
        f.write("source:   %s (local checkout)\n" % os.path.basename(src_dir))
        f.write("upstream: https://github.com/MidhunkMadhu/MD_openmm\n")
        f.write("commit:   %s\n" % git_commit(src_dir))
        f.write("date:     %s\n\n" % datetime.date.today().isoformat())
        f.write("sha256 of source files:\n")
        for m in [PRODUCTION] + MODULES:
            f.write("  %s  %s\n" % (sha256(os.path.join(src_dir, m)), m))
        f.write("\nproduction_helpers.py functions (%d): %s\n" % (len(funcs), ", ".join(funcs)))
        f.write("\nomm_*.py files were generated by CHARMM-GUI (headers kept).\n")

    print("vendored %d functions + %d modules into %s" % (len(funcs), len(MODULES), dest))


if __name__ == "__main__":
    main()
